# Generated by Django 5.2.7 on 2025-10-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='schools/'),
        ),
    ]
