# Generated by Django 5.2.7 on 2025-10-27 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_school_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maxima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_attendue', models.DecimalField(decimal_places=2, help_text='Note maximale attendue (ex: 50)', max_digits=5)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maximas', to='core.classe')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maximas_crees', to=settings.AUTH_USER_MODEL)),
                ('matieres', models.ManyToManyField(help_text='Sélectionnez les matières concernées par cette note maximale', related_name='maximas', to='core.matiere')),
                ('periode_primaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maximas_primaire', to='core.periodeprimaire')),
                ('periode_secondaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maximas_secondaire', to='core.periodesecondaire')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maximas', to='core.school')),
            ],
            options={
                'verbose_name_plural': 'Maximas',
                'ordering': ['-date_creation'],
            },
        ),
    ]
