# Generated by Django 5.2.7 on 2025-10-28 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_maxima'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemestreTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_totale_attendue', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('totaux_matieres', models.JSONField(blank=True, default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres_totaux', to='core.classe')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semestres_totaux_crees', to=settings.AUTH_USER_MODEL)),
                ('maximas', models.ManyToManyField(related_name='semestres_totaux', to='core.maxima')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres_totaux', to='core.school')),
            ],
            options={
                'verbose_name': 'Total du Semestre',
                'verbose_name_plural': 'Totaux des Semestres',
            },
        ),
    ]
