# Generated by Django 5.2.7 on 2025-10-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_semestretotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestretotal',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
