# Generated by Django 5.2.7 on 2025-10-28 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_semestretotal_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='eleve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_eleves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eleve',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
