# Generated by Django 5.2.7 on 2025-11-13 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_eleve_eleve_eleve_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpreuveNoteObtenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_epreuve', models.CharField(max_length=255)),
                ('date_epreuve', models.DateField()),
                ('note_epreuve_attendue', models.FloatField()),
                ('note_epreuve_obtenue', models.FloatField(blank=True, null=True)),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_epreuves', to='core.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='core.matiere')),
                ('periode_primaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.periodeprimaire')),
                ('periode_secondaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.periodesecondaire')),
            ],
        ),
    ]
