# Generated by Django 5.2.7 on 2025-11-14 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_epreuvenoteobtenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('note_attendue', models.FloatField()),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matiere')),
                ('periode_primaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.periodeprimaire')),
                ('periode_secondaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.periodesecondaire')),
            ],
        ),
        migrations.CreateModel(
            name='NoteEpreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(blank=True, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_epreuves', to='core.eleve')),
                ('epreuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.epreuve')),
            ],
            options={
                'unique_together': {('epreuve', 'eleve')},
            },
        ),
        migrations.DeleteModel(
            name='EpreuveNoteObtenue',
        ),
    ]
