# Generated by Django 5.2.7 on 2025-11-19 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_epreuve_noteepreuve_delete_epreuvenoteobtenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='mot_des_eleves',
            field=models.TextField(blank=True, help_text='Petit message des élèves pour cette année', null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='image_profil',
            field=models.ImageField(blank=True, null=True, upload_to='eleves/profil/'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='photo_entiere',
            field=models.ImageField(blank=True, null=True, upload_to='eleves/complet/'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='FondateurSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('biographie', models.TextField(blank=True, null=True)),
                ('message_annee', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='fondateurs/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fondateurs', to='core.school')),
            ],
            options={
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='InfoSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=20)),
                ('presentation', models.TextField(blank=True, null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('valeurs', models.TextField(blank=True, null=True)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('remerciements', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='school_images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='core.school')),
            ],
            options={
                'unique_together': {('school', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='InfoSchoolPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school_info_gallery/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.infoschool')),
            ],
        ),
    ]
