# Generated by Django 5.2.7 on 2025-11-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_classe_mot_des_eleves_eleve_image_profil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoschool',
            name='galerie_image',
            field=models.ImageField(blank=True, null=True, upload_to='school_info_gallery/', verbose_name='Image galerie'),
        ),
    ]
