# Generated by Django 5.2.7 on 2025-11-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_infoschool_galerie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoschool',
            name='galerie_image',
            field=models.ImageField(blank=True, null=True, upload_to='school_info_gallery/', verbose_name='Image de couverture'),
        ),
    ]
