# Generated by Django 5.2.7 on 2025-11-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_infoschool_galerie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='photo_classe',
            field=models.ImageField(blank=True, help_text='Photo de la classe ou de la salle', null=True, upload_to='classes/photos/'),
        ),
    ]
