# Generated by Django 5.2.7 on 2025-10-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('commune', models.CharField(help_text='Entrez la commune manuellement', max_length=100)),
                ('description', models.TextField()),
                ('type_bien', models.CharField(choices=[('maison', 'Maison'), ('appartement', 'Appartement'), ('hotel', 'Hôtel'), ('guesthouse', 'Guesthouse'), ('boutique', 'Boutique'), ('parcelle vide', 'Parcelle vide'), ('terrain agricole', 'Terrain agricole'), ('bureau', 'Bureau'), ('autres', 'Autres')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted', models.BooleanField(default=False)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/requests/')),
            ],
        ),
    ]
